document.addEventListener("DOMContentLoaded",()=>{
 const user=getCurrentUser();if(!user||user.role!=="admin"){location.href="login.html";return}renderAdmin();
});
function renderAdmin(){
 const users=getFromStorage(STORAGE_KEYS.users,[]),c=getCampaigns(),tx=getTransactions(),counts=s=>tx.filter(t=>t.status===s).length;
 document.getElementById("adminStats").innerHTML=`<div class="stat-card"><span>${users.length}</span><small>Total Users</small></div><div class="stat-card"><span>${c.length}</span><small>Total Campaigns</small></div><div class="stat-card"><span>${formatINR(tx.reduce((s,t)=>s+t.amount,0))}</span><small>Total Donations</small></div><div class="stat-card"><span>${counts("SUCCESS")}</span><small>Successful Payments</small></div><div class="stat-card"><span>${counts("PENDING")}</span><small>Pending Payments</small></div><div class="stat-card"><span>${counts("FAILED")}</span><small>Failed Payments</small></div>`;
 document.getElementById("adminContent").innerHTML=`<div class="panel admin-panel"><div class="panel-heading"><div><span class="eyebrow">Moderation</span><h2>Campaign verification</h2></div></div><div class="table-wrap"><table><thead><tr><th>Campaign</th><th>Creator</th><th>Status</th><th>Verification</th><th>Actions</th></tr></thead><tbody>${c.map(x=>`<tr><td>${escapeHtml(x.title)}</td><td>${escapeHtml(x.creator)}</td><td><span class="status-pill">${x.status}</span></td><td><span class="status-pill ${x.verification.toLowerCase()}">${x.verification}</span></td><td class="actions"><button class="mini-btn" data-approve="${x.id}">Approve</button><button class="mini-btn" data-reject="${x.id}">Reject</button><button class="mini-btn danger" data-suspend="${x.id}">Suspend</button></td></tr>`).join("")}</tbody></table></div></div><div class="panel admin-panel"><div class="panel-heading"><div><span class="eyebrow">Transactions</span><h2>Payment operations</h2></div></div><div class="table-wrap"><table><thead><tr><th>Transaction</th><th>Campaign</th><th>Amount</th><th>Method</th><th>Status</th><th>Action</th></tr></thead><tbody>${tx.map(t=>`<tr><td>${t.transactionId}</td><td>${escapeHtml(getCampaign(t.campaignId)?.title||"Unknown")}</td><td>${formatINR(t.amount)}</td><td>${t.paymentMethod}</td><td><span class="status-pill ${t.status.toLowerCase()}">${t.status}</span></td><td>${t.status==="SUCCESS"?`<button class="mini-btn" data-refund="${t.transactionId}">Refund</button>`:"—"}</td></tr>`).join("")}</tbody></table></div></div><div class="panel admin-panel"><div class="panel-heading"><div><span class="eyebrow">Users</span><h2>User directory</h2></div></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Joined</th></tr></thead><tbody>${users.map(u=>`<tr><td>${escapeHtml(u.name)}</td><td>${escapeHtml(u.email)}</td><td>${u.role}</td><td>${u.status}</td><td>${u.joined}</td></tr>`).join("")}</tbody></table></div></div>`;
 document.querySelectorAll("[data-approve]").forEach(b=>b.onclick=()=>{updateCampaign(b.dataset.approve,{verification:"Verified"});showToast("Campaign marked verified","success");renderAdmin();});
 document.querySelectorAll("[data-reject]").forEach(b=>b.onclick=()=>{updateCampaign(b.dataset.reject,{verification:"Rejected"});showToast("Campaign rejected","info");renderAdmin();});
 document.querySelectorAll("[data-suspend]").forEach(b=>b.onclick=()=>{updateCampaign(b.dataset.suspend,{status:"Cancelled"});showToast("Campaign suspended","info");renderAdmin();});
 document.querySelectorAll("[data-refund]").forEach(b=>b.onclick=()=>{const all=getTransactions(),i=all.findIndex(t=>t.transactionId===b.dataset.refund);if(i>=0){all[i]={...all[i],status:"REFUNDED",refundId:generateRefundId(),updatedAt:new Date().toISOString()};saveToStorage(STORAGE_KEYS.transactions,all);showNotification("Refund simulation completed","success");renderAdmin();}});
}