document.addEventListener("DOMContentLoaded",()=>{
 const user=getCurrentUser();if(!user){location.href="login.html";return}
 const tx=getTransactions().filter(t=>t.donorId===user.id), campaigns=getCampaigns(), mine=campaigns.filter(c=>c.creator===user.name), role=user.role;
 document.getElementById("dashboardTitle").textContent=role==="admin"?"Admin Activity":`Hi, ${user.name.split(" ")[0]} 👋`;
 document.getElementById("dashboardSubtitle").textContent=role==="admin"?"Use the admin dashboard for platform controls.":"Track your contributions, saved campaigns and impact.";
 if(role==="admin"){document.getElementById("dashboardContent").innerHTML=`<div class="panel"><h2>Admin access</h2><p>Open the dedicated admin control center for moderation and refund simulation.</p><a class="btn btn-primary" href="admin.html">Open Admin Dashboard</a></div>`;return}
 const success=tx.filter(t=>t.status==="SUCCESS"),pending=tx.filter(t=>t.status==="PENDING"),total=success.reduce((s,t)=>s+t.amount,0),saved=getFromStorage(STORAGE_KEYS.savedCampaigns,[]).map(id=>getCampaign(id)).filter(Boolean);
 document.getElementById("dashboardStats").innerHTML=`<div class="stat-card"><span>${formatINR(total)}</span><small>Total Donated</small></div><div class="stat-card"><span>${new Set(tx.map(t=>t.campaignId)).size}</span><small>Campaigns Supported</small></div><div class="stat-card"><span>${success.length}</span><small>Successful Payments</small></div><div class="stat-card"><span>${pending.length}</span><small>Pending Payments</small></div>`;
 document.getElementById("dashboardContent").innerHTML=`<div class="dashboard-grid"><div class="panel"><div class="panel-heading"><div><span class="eyebrow">Donation history</span><h2>My Contributions</h2></div><a href="campaigns.html" class="text-link">Discover more</a></div>${tx.length?`<div class="table-wrap"><table><thead><tr><th>Transaction</th><th>Campaign</th><th>Amount</th><th>Status</th><th>Date</th></tr></thead><tbody>${tx.map(t=>`<tr><td>${t.transactionId}</td><td>${escapeHtml(getCampaign(t.campaignId)?.title||"Unknown")}</td><td>${formatINR(t.amount)}</td><td><span class="status-pill ${t.status.toLowerCase()}">${t.status}</span></td><td>${new Date(t.createdAt).toLocaleDateString("en-IN")}</td></tr>`).join("")}</tbody></table></div>`:`<div class="empty-state compact"><i class="fa-regular fa-credit-card"></i><h3>No Transactions Yet</h3><p>Your donation history will appear here.</p></div>`}</div><div class="panel"><span class="eyebrow">Your impact</span><h2>Make the numbers meaningful.</h2><div class="impact-summary"><div><strong>${Math.max(1,Math.round(total/500))}</strong><span>Students supported</span></div><div><strong>${Math.max(1,Math.round(total/150))}</strong><span>Meals funded</span></div><div><strong>${Math.max(1,Math.round(total/50))}L</strong><span>Water provided</span></div></div></div></div><div class="panel saved-panel"><div class="panel-heading"><div><span class="eyebrow">Saved campaigns</span><h2>Come back to what matters.</h2></div></div>${saved.length?`<div class="campaign-grid">${saved.map(campaignCard).join("")}</div>`:`<div class="empty-state compact"><i class="fa-regular fa-heart"></i><h3>No Saved Campaigns</h3><p>You haven't saved any campaigns yet.</p><a class="btn btn-primary" href="campaigns.html">Explore Campaigns</a></div>`}</div>`;
});